=== Atralupus/hub/data/mod.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "maxLength": 30
        },
        "title": {
            "type": "string",
            "maxLength": 10
        },
        "developer": {
            "type": "string",
            "maxLength": 15
        },
        "summary": {
            "type": "string",
            "maxLength": 120
        },
        "githubLink": {
            "type": "string",
            "pattern": "^https:\\/\\/github\\.com\\/[^\\/]+\\/[^\\/]+(?:\\/tree\\/[^\\/]+(?:\\/.*)?)?$"
        },
        "siteLink": {
            "type": "string"
        },
        "thumbnailExists": {
            "type": "boolean"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string",
                "description": "The value must exist in data/mod-tags.json",
                "enum": [
                    "website",
                    "unity",
                    "arena",
                    "simulator",
                    "Library",
                    "JavaScript",
                    "TypeScript"
                ]
            }
        }
    },
    "required": [
        "id",
        "title",
        "developer",
        "summary",
        "githubLink",
        "thumbnailExists",
        "tags"
    ]
}

=== Atralupus/hub/data/mods/planetarium.9cscan.json
{
    "id": "planetarium.9cscan",
    "title": "9cscan.com",
    "developer": "hxad",
    "summary": "9cscan is a Block Explorer and Analytics Platform for Nine Chronicles",
    "githubLink": "https://github.com/planetarium/9cscan.com",
    "thumbnailExists": true,
    "tags": [
        "website"
    ]
}

=== Atralupus/hub/data/mods/planetarium.lib9c-js.json
{
    "id": "planetarium.lib9c-js",
    "title": "@planetarium/lib9c",
    "developer": "Planetarium",
    "summary": "A library to create Nine Chronicles actions easily with JavaScript/TypeScript",
    "githubLink": "https://github.com/planetarium/lib9c/tree/development/@planetarium/lib9c",
    "thumbnailExists": false,
    "tags": [
        "Library",
        "JavaScript",
        "TypeScript"
    ]
}
